name: old_bugs
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.3.7
  provider: ^6.0.2
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true
